/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/door.glb --types --output temp_door_model.tsx 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Muro_Marco: THREE.Mesh
    Hoja_Puerta: THREE.Mesh
    Cubo: THREE.Mesh
  }
  materials: {
    Mat_Dungeon_Door: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/door.glb') as GLTFResult
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Muro_Marco.geometry} material={materials.Mat_Dungeon_Door} position={[-1.504, 0.083, 1.491]} rotation={[-0.015, 0.009, 0.011]} scale={[0.52, 0.175, 0.52]} />
      <mesh geometry={nodes.Hoja_Puerta.geometry} material={materials.Mat_Dungeon_Door} position={[-0.373, 0.9, 0]} rotation={[-0.008, 0, 0]} scale={[0.118, 1.78, 0.12]} />
      <mesh geometry={nodes.Cubo.geometry} material={nodes.Cubo.material} position={[0, 1, 0]} scale={[1, 2, 1]} />
    </group>
  )
}

useGLTF.preload('/door.glb')
