/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/door.glb --output src/components/game/3d/DoorModel.tsx --types 
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'

type GLTFResult = GLTF & {
  nodes: {
    Hoja_Puerta: THREE.Mesh
  }
  materials: {
    Mat_Dungeon_Door: THREE.MeshStandardMaterial
  }
}

type DoorModelProps = React.ComponentProps<'group'> & {
  isOpen?: boolean;
}

export function Model({ isOpen = false, ...props }: DoorModelProps) {
  const { nodes, materials } = useGLTF('/models/door.glb') as unknown as GLTFResult
  const doorRef = useRef<THREE.Mesh>(null)

  // Debugging: Log nodes to check what we actually received
  if (!nodes || !nodes.Hoja_Puerta) {
    console.error('DoorModel: Nodes or Hoja_Puerta not found:', nodes);
    return null;
  }

  // Animación simple de apertura
  useFrame((_state, delta) => {
    if (doorRef.current) {
      const targetRotation = isOpen ? Math.PI / 2 : 0; // 90 grados si está abierta
      // Interpolación suave
      // Nota: Mantenemos la rotación original en X/Z y solo animamos Y
      // Sin embargo, si la rotación original en Y es 0, podemos asignar directamente.
      doorRef.current.rotation.y = THREE.MathUtils.lerp(
        doorRef.current.rotation.y,
        targetRotation,
        delta * 5
      );
    }
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        ref={doorRef}
        geometry={nodes.Hoja_Puerta.geometry}
        material={materials.Mat_Dungeon_Door}
        position={[-0.373, 0.9, 0]}
        rotation={[-0.008, 0, 0]}
        scale={[0.118, 1.78, 0.12]}
      />
    </group>
  )
}

useGLTF.preload('/models/door.glb')
