/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/floor.glb --output src/components/game/3d/FloorModel.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Muro_Piedra_Final: THREE.Mesh
    Suelo_Piedra_Oscura: THREE.Mesh
    Suelo_1x1_Piedra_Oscura: THREE.Mesh
    Suelo_1x1_Cuadrado_Rocoso_Muy_Oscuro: THREE.Mesh
    Suelo_1x1_Rocoso: THREE.Mesh
    Suelo_1x1_Rocoso001: THREE.Mesh
    Suelo_1x1_Rocoso002: THREE.Mesh
    Suelo_1x1_Rocoso003: THREE.Mesh
    Suelo_1x1_Rocoso_Muy_Oscuro: THREE.Mesh
  }
  materials: {
    Material_Inteligente_Piedra: THREE.MeshStandardMaterial
    Material_Suelo_Piedra_Oscura: THREE.MeshStandardMaterial
    Material_Suelo_Piedra_Oscura_Rocosa: THREE.MeshStandardMaterial
    Material_Suelo_Piedra_Muy_Oscura_Rocosa: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/floor.glb') as GLTFResult

  // ✅ Configuración Manual de Material (Fallback por falta de Vertex Colors)
  React.useLayoutEffect(() => {
    Object.values(materials).forEach((mat) => {
      // ❌ Vertex Colors desactivados porque el modelo venía negro
      mat.vertexColors = false;

      // 🎨 Color Manual: Piedra Gris/Marrón Oscura
      mat.color = new THREE.Color('#57534e'); // Stone-700 approx

      // ✨ PBR: Piedra un poco rugosa pero con algo de especularidad
      mat.roughness = 0.8;
      mat.metalness = 0.2;

      if (mat.map) mat.map = null;
      mat.needsUpdate = true;
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh
        // ✅ Usamos el nodo correcto
        geometry={nodes.Suelo_1x1_Cuadrado_Rocoso_Muy_Oscuro.geometry}
        // Material corregido
        material={nodes.Suelo_1x1_Cuadrado_Rocoso_Muy_Oscuro.material || Object.values(materials)[0]}
        receiveShadow
      />
    </group>
  )
}

useGLTF.preload('/models/floor.glb')
