/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/torch.glb --output src/components/game/3d/TorchModel.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Cubo9650: THREE.Mesh
    Cubo9650_1: THREE.Mesh
    Cubo9650_2: THREE.Mesh
  }
  materials: {
    Mat_Hierro: THREE.MeshStandardMaterial
    Mat_Madera: THREE.MeshStandardMaterial
    Mat_Fuego: THREE.MeshStandardMaterial
  }
  animations: THREE.AnimationClip[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/torch.glb') as GLTFResult

  // Configuración de materiales
  React.useLayoutEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.vertexColors = true;
      mat.roughness = 0.9;
      mat.metalness = 0.0;
    });

    // Configuración especial para el fuego
    if (materials.Mat_Fuego) {
      materials.Mat_Fuego.emissive = new THREE.Color(1, 0.5, 0); // Naranja brillante
      materials.Mat_Fuego.emissiveIntensity = 2.0; // Muy brillante
      materials.Mat_Fuego.toneMapped = false; // No oscurecer por tone mapping
    }
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group scale={[0.15, 0.25, 0.05]}>
        <mesh geometry={nodes.Cubo9650.geometry} material={materials.Mat_Hierro} castShadow />
        <mesh geometry={nodes.Cubo9650_1.geometry} material={materials.Mat_Madera} castShadow />
        <mesh geometry={nodes.Cubo9650_2.geometry} material={materials.Mat_Fuego} />
        {/* Luz integrada en la antorcha */}
        <pointLight position={[0, 2, 0]} intensity={1.5} distance={5} decay={2} color="#ffaa00" castShadow />
      </group>
    </group>
  )
}

useGLTF.preload('/models/torch.glb')
