/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/wallcorner.glb --output src/components/game/3d/WallCornerModel.tsx --types 
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    Bloque_1x05x2: THREE.Mesh
    Suelo_1x1_Cuadrado_Rocoso_Muy_Oscuro: THREE.Mesh
    Bloque_1x05x2001: THREE.Mesh
  }
  materials: {
    ['Mat_Solido_Oscuro.003']: THREE.MeshStandardMaterial
    Material_Suelo_Piedra_Muy_Oscura_Rocosa: THREE.MeshStandardMaterial
  }
  animations: GLTFAction[]
}

export function Model(props: React.JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/models/wallcorner.glb') as unknown as GLTFResult

  React.useLayoutEffect(() => {
    Object.values(materials).forEach((mat) => {
      mat.map = null;
      mat.vertexColors = false;
      mat.color = new THREE.Color('#64748b'); // Stone Grey
      mat.roughness = 0.9;
      mat.metalness = 0.0;
      mat.emissive = new THREE.Color(0, 0, 0);
      mat.needsUpdate = true;
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Bloque_1x05x2.geometry} material={materials['Mat_Solido_Oscuro.003']} position={[0, 1, 0]} />
      {/* Hide included floor to avoid z-fighting */}
      {/* <mesh geometry={nodes.Suelo_1x1_Cuadrado_Rocoso_Muy_Oscuro.geometry} material={materials.Material_Suelo_Piedra_Muy_Oscura_Rocosa} position={[0.247, 0, 0]} /> */}
      <mesh geometry={nodes.Bloque_1x05x2001.geometry} material={materials['Mat_Solido_Oscuro.003']} position={[0.26, 0.995, -0.25]} rotation={[-Math.PI, 1.564, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/wallcorner.glb')
